baseURL = "https://jfparie.github.io/"
languageCode = "nl"

[languages]
  [languages.nl]
    disabled = false
    languageCode = 'nl'
    languageDirection = 'ltr'
    languageName = 'Nederlands'
    title = ''
    weight = 0

    [languages.nl.menus]
      [[languages.nl.menus.header]]
        name = 'Home'
        URL = '/'
        weight = 1
      [[languages.nl.menus.header]]
        name = 'Artikel & Opinie'
        URL = '/artikel-en-opinie'
        weight = 2
      [[languages.nl.menus.header]]
        name = 'Lezingen & Debat'
        URL = '/lezingen-en-debat'
        weight = 3
      [[languages.nl.menus.header]]
      name = "Podcasts & Interviews"
      URL = "/podcasts-en-interviews"
      weight = 4

  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = ''
    weight = 1

    [languages.en.menus]
      [[languages.en.menus.header]]
        name = 'Home'
        URL = '/'
        weight = 1
      [[languages.en.menus.header]]
        name = 'Articles & Opinion'
        URL = '/artikel-en-opinie'
        weight = 2
      [[languages.en.menus.header]]
        name = 'Lezingen & Debat'
        URL = '/lezingen-en-debat'
        weight = 3
      [[languages.en.menus.header]]
      name = "Podcasts & Interviews"
      URL = "/podcasts-en-interviews"
      weight = 4

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/custom.css"