[[header]]
    URL = '/'
    weight = 1
[[header]]
    name = 'Home'
    URL = '/'
    weight = 2
[[header]]
    name = 'Articles & Opinion'
    URL = '/artikel-en-opinie'
    weight = 3
[[header]]
    name = 'Lezingen & Debat'
    URL = '/lezingen-en-debat'
    weight = 4
[[header]]
    name = "Podcasts & Interviews"
    URL = "/podcasts-en-interviews"
    weight = 5