[[header]]
  URL = '/nl'
  weight = 1
[[header]]
  name = 'Artikel & Opinie'
  URL = '/nl/artikel-en-opinie'
  weight = 2
[[header]]
  name = 'Lezingen & Debat'
  URL = '/nl/lezingen-en-debat'
  weight = 3
[[header]]
  name = "Podcasts & Interviews"
  URL = "/nl/podcasts-en-interviews"
  weight = 4