[[header]]
    pageref = '/'
    weight = 1
[[header]]
    name = 'Home'
    pageref = '/'
    weight = 2
[[header]]
    name = 'Articles & Opinion'
    pageref = '/artikel-en-opinie'
    weight = 3
[[header]]
    name = 'Lezingen & Debat'
    pageref = '/lezingen-en-debat'
    weight = 4
[[header]]
    name = "Podcasts & Interviews"
    pageref = "/podcasts-en-interviews"
    weight = 5